[package]
name = "cpu-test"
version = "0.1.0"
authors = ["david <wizdave97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpu = {path = '../cpu'}
piston_window = "0.120.0"
find_folder = "0.3.0"
