use crate::Cpu;
use std::{cell::RefCell, rc::Rc};

pub struct Instruction<'a> {
    pub name: &'a str,
    pub addr_name: &'a str,
    pub operation: fn(&mut Cpu) -> u8,
    pub address_mode: fn(&mut Cpu) -> u8,
    pub cycles: u8,
}

// This is a 16 * 16 matrix representing the processor opcodes for the 6502 cpu
pub struct LookUpTable<'a> {
    pub table: Vec<Instruction<'a>>,
}

impl<'a> LookUpTable<'a> {
    pub fn new() -> LookUpTable<'a> {
        LookUpTable {
            table: vec![
                //ROW 0
                Instruction {
                    name: "BRK",
                    cycles: 7,
                    addr_name: "IMP",
                    operation: Cpu::BRK,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "ORA",
                    cycles: 6,
                    addr_name: "INDX",
                    operation: Cpu::ORA,
                    address_mode: Cpu::INDX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "ORA",
                    cycles: 3,
                    addr_name: "ZP",
                    operation: Cpu::ORA,
                    address_mode: Cpu::ZP,
                },
                Instruction {
                    name: "ASL",
                    cycles: 5,
                    addr_name: "ZP",
                    operation: Cpu::ASL,
                    address_mode: Cpu::ZP,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "PHP",
                    cycles: 3,
                    addr_name: "IMP",
                    operation: Cpu::PHP,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "ORA",
                    cycles: 2,
                    addr_name: "IMM",
                    operation: Cpu::ORA,
                    address_mode: Cpu::IMM,
                },
                Instruction {
                    name: "ASL",
                    cycles: 2,
                    addr_name: "ACC",
                    operation: Cpu::ASL,
                    address_mode: Cpu::ACC,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "ORA",
                    cycles: 4,
                    addr_name: "ABS",
                    operation: Cpu::ORA,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "ASL",
                    cycles: 6,
                    addr_name: "ABS",
                    operation: Cpu::ASL,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                // ROW 1
                Instruction {
                    name: "BPL",
                    cycles: 2,
                    addr_name: "REL",
                    operation: Cpu::BPL,
                    address_mode: Cpu::REL,
                },
                Instruction {
                    name: "ORA",
                    cycles: 5,
                    addr_name: "INDY",
                    operation: Cpu::ORA,
                    address_mode: Cpu::INDY,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "ORA",
                    cycles: 4,
                    addr_name: "ZPX",
                    operation: Cpu::ORA,
                    address_mode: Cpu::ZPX,
                },
                Instruction {
                    name: "ASL",
                    cycles: 6,
                    addr_name: "ZPX",
                    operation: Cpu::ASL,
                    address_mode: Cpu::ZPX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "CLC",
                    cycles: 2,
                    addr_name: "IMP",
                    operation: Cpu::CLC,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "ORA",
                    cycles: 4,
                    addr_name: "ABSY",
                    operation: Cpu::ORA,
                    address_mode: Cpu::ABSY,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "ORA",
                    cycles: 4,
                    addr_name: "ABSX",
                    operation: Cpu::ORA,
                    address_mode: Cpu::ABSX,
                },
                Instruction {
                    name: "ASL",
                    cycles: 7,
                    addr_name: "ABSX",
                    operation: Cpu::ASL,
                    address_mode: Cpu::ABSX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                // ROW 2
                Instruction {
                    name: "JSR",
                    cycles: 6,
                    addr_name: "ABS",
                    operation: Cpu::JSR,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "AND",
                    cycles: 6,
                    addr_name: "INDX",
                    operation: Cpu::AND,
                    address_mode: Cpu::INDX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "BIT",
                    cycles: 3,
                    addr_name: "ZP",
                    operation: Cpu::BIT,
                    address_mode: Cpu::ZP,
                },
                Instruction {
                    name: "AND",
                    cycles: 3,
                    addr_name: "ZP",
                    operation: Cpu::AND,
                    address_mode: Cpu::ZP,
                },
                Instruction {
                    name: "ROL",
                    cycles: 5,
                    addr_name: "ZP",
                    operation: Cpu::ROL,
                    address_mode: Cpu::ZP,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "PLP",
                    cycles: 4,
                    addr_name: "IMP",
                    operation: Cpu::PLP,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "AND",
                    cycles: 2,
                    addr_name: "IMM",
                    operation: Cpu::AND,
                    address_mode: Cpu::IMM,
                },
                Instruction {
                    name: "ROL",
                    cycles: 2,
                    addr_name: "ACC",
                    operation: Cpu::ROL,
                    address_mode: Cpu::ACC,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "BIT",
                    cycles: 4,
                    addr_name: "ABS",
                    operation: Cpu::BIT,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "AND",
                    cycles: 4,
                    addr_name: "ABS",
                    operation: Cpu::AND,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "ROL",
                    cycles: 6,
                    addr_name: "ABS",
                    operation: Cpu::ROL,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                // ROW 3
                Instruction {
                    name: "BMI",
                    cycles: 2,
                    addr_name: "REL",
                    operation: Cpu::BMI,
                    address_mode: Cpu::REL,
                },
                Instruction {
                    name: "AND",
                    cycles: 5,
                    addr_name: "INDY",
                    operation: Cpu::AND,
                    address_mode: Cpu::INDY,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "AND",
                    cycles: 4,
                    addr_name: "ZPX",
                    operation: Cpu::AND,
                    address_mode: Cpu::ZPX,
                },
                Instruction {
                    name: "ROL",
                    cycles: 6,
                    addr_name: "ZPX",
                    operation: Cpu::ROL,
                    address_mode: Cpu::ZPX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "SEC",
                    cycles: 2,
                    addr_name: "IMP",
                    operation: Cpu::SEC,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "AND",
                    cycles: 4,
                    addr_name: "ABSY",
                    operation: Cpu::AND,
                    address_mode: Cpu::ABSY,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "AND",
                    cycles: 4,
                    addr_name: "ABSX",
                    operation: Cpu::AND,
                    address_mode: Cpu::ABSX,
                },
                Instruction {
                    name: "ROL",
                    cycles: 7,
                    addr_name: "ABSX",
                    operation: Cpu::ROL,
                    address_mode: Cpu::ABSX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                // ROW 4
                Instruction {
                    name: "RTI",
                    cycles: 6,
                    addr_name: "IMP",
                    operation: Cpu::RTI,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "EOR",
                    cycles: 6,
                    addr_name: "INDX",
                    operation: Cpu::EOR,
                    address_mode: Cpu::INDX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "EOR",
                    cycles: 3,
                    addr_name: "ZP",
                    operation: Cpu::EOR,
                    address_mode: Cpu::ZP,
                },
                Instruction {
                    name: "LSR",
                    cycles: 5,
                    addr_name: "ZP",
                    operation: Cpu::LSR,
                    address_mode: Cpu::ZP,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "PHA",
                    cycles: 3,
                    addr_name: "IMP",
                    operation: Cpu::PHA,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "EOR",
                    cycles: 2,
                    addr_name: "IMM",
                    operation: Cpu::EOR,
                    address_mode: Cpu::IMM,
                },
                Instruction {
                    name: "LSR",
                    cycles: 2,
                    addr_name: "ACC",
                    operation: Cpu::LSR,
                    address_mode: Cpu::ACC,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "JMP",
                    cycles: 3,
                    addr_name: "ABS",
                    operation: Cpu::JMP,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "EOR",
                    cycles: 4,
                    addr_name: "ABS",
                    operation: Cpu::EOR,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "LSR",
                    cycles: 6,
                    addr_name: "ABS",
                    operation: Cpu::LSR,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                // ROW 5
                Instruction {
                    name: "BVC",
                    cycles: 2,
                    addr_name: "REL",
                    operation: Cpu::BVC,
                    address_mode: Cpu::REL,
                },
                Instruction {
                    name: "EOR",
                    cycles: 5,
                    addr_name: "INDY",
                    operation: Cpu::EOR,
                    address_mode: Cpu::INDY,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "EOR",
                    cycles: 4,
                    addr_name: "ZPX",
                    operation: Cpu::EOR,
                    address_mode: Cpu::ZPX,
                },
                Instruction {
                    name: "LSR",
                    cycles: 6,
                    addr_name: "ZPX",
                    operation: Cpu::LSR,
                    address_mode: Cpu::ZPX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "CLI",
                    cycles: 2,
                    addr_name: "IMP",
                    operation: Cpu::CLI,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "EOR",
                    cycles: 4,
                    addr_name: "ABSY",
                    operation: Cpu::EOR,
                    address_mode: Cpu::ABSY,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "EOR",
                    cycles: 4,
                    addr_name: "ABSX",
                    operation: Cpu::EOR,
                    address_mode: Cpu::ABSX,
                },
                Instruction {
                    name: "LSR",
                    cycles: 7,
                    addr_name: "ABSX",
                    operation: Cpu::LSR,
                    address_mode: Cpu::ABSX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                // ROW 6
                Instruction {
                    name: "RTS",
                    cycles: 6,
                    addr_name: "IMP",
                    operation: Cpu::RTS,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "ADC",
                    cycles: 6,
                    addr_name: "INDX",
                    operation: Cpu::ADC,
                    address_mode: Cpu::INDX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "ADC",
                    cycles: 3,
                    addr_name: "ZP",
                    operation: Cpu::ADC,
                    address_mode: Cpu::ZP,
                },
                Instruction {
                    name: "ROR",
                    cycles: 5,
                    addr_name: "ZP",
                    operation: Cpu::ROR,
                    address_mode: Cpu::ZP,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "PLA",
                    cycles: 4,
                    addr_name: "IMP",
                    operation: Cpu::PLA,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "ADC",
                    cycles: 2,
                    addr_name: "IMM",
                    operation: Cpu::ADC,
                    address_mode: Cpu::IMM,
                },
                Instruction {
                    name: "ROR",
                    cycles: 2,
                    addr_name: "ACC",
                    operation: Cpu::ROR,
                    address_mode: Cpu::ACC,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "JMP",
                    cycles: 5,
                    addr_name: "ABSIND",
                    operation: Cpu::JMP,
                    address_mode: Cpu::ABSIND,
                },
                Instruction {
                    name: "ADC",
                    cycles: 4,
                    addr_name: "ABS",
                    operation: Cpu::ADC,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "ROR",
                    cycles: 6,
                    addr_name: "ABS",
                    operation: Cpu::ROR,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                // ROW 7
                Instruction {
                    name: "BVS",
                    cycles: 2,
                    addr_name: "REL",
                    operation: Cpu::BVS,
                    address_mode: Cpu::REL,
                },
                Instruction {
                    name: "ADC",
                    cycles: 5,
                    addr_name: "INDY",
                    operation: Cpu::ADC,
                    address_mode: Cpu::INDY,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "ADC",
                    cycles: 4,
                    addr_name: "ZPX",
                    operation: Cpu::ADC,
                    address_mode: Cpu::ZPX,
                },
                Instruction {
                    name: "ROR",
                    cycles: 6,
                    addr_name: "ZPX",
                    operation: Cpu::ROR,
                    address_mode: Cpu::ZPX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "SEI",
                    cycles: 2,
                    addr_name: "IMP",
                    operation: Cpu::SEI,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "ADC",
                    cycles: 4,
                    addr_name: "ABSY",
                    operation: Cpu::ADC,
                    address_mode: Cpu::ABSY,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "ADC",
                    cycles: 4,
                    addr_name: "ABSX",
                    operation: Cpu::ADC,
                    address_mode: Cpu::ABSX,
                },
                Instruction {
                    name: "ROR",
                    cycles: 7,
                    addr_name: "ABSX",
                    operation: Cpu::ROR,
                    address_mode: Cpu::ABSX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                // ROW 8
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "STA",
                    cycles: 6,
                    addr_name: "INDX",
                    operation: Cpu::STA,
                    address_mode: Cpu::INDX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "STY",
                    cycles: 3,
                    addr_name: "ZP",
                    operation: Cpu::STY,
                    address_mode: Cpu::ZP,
                },
                Instruction {
                    name: "STA",
                    cycles: 3,
                    addr_name: "ZP",
                    operation: Cpu::STA,
                    address_mode: Cpu::ZP,
                },
                Instruction {
                    name: "STX",
                    cycles: 3,
                    addr_name: "ZP",
                    operation: Cpu::STX,
                    address_mode: Cpu::ZP,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "DEY",
                    cycles: 2,
                    addr_name: "IMP",
                    operation: Cpu::DEY,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "TXA",
                    cycles: 2,
                    addr_name: "IMP",
                    operation: Cpu::TXA,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "STY",
                    cycles: 4,
                    addr_name: "ABS",
                    operation: Cpu::STY,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "STA",
                    cycles: 4,
                    addr_name: "ABS",
                    operation: Cpu::STA,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "STX",
                    cycles: 4,
                    addr_name: "ABS",
                    operation: Cpu::STX,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                // ROW 9
                Instruction {
                    name: "BCC",
                    cycles: 2,
                    addr_name: "REL",
                    operation: Cpu::BCC,
                    address_mode: Cpu::REL,
                },
                Instruction {
                    name: "STA",
                    cycles: 6,
                    addr_name: "INDY",
                    operation: Cpu::STA,
                    address_mode: Cpu::INDY,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "STY",
                    cycles: 4,
                    addr_name: "ZPX",
                    operation: Cpu::STY,
                    address_mode: Cpu::ZPX,
                },
                Instruction {
                    name: "STA",
                    cycles: 4,
                    addr_name: "ZPX",
                    operation: Cpu::STA,
                    address_mode: Cpu::ZPX,
                },
                Instruction {
                    name: "STX",
                    cycles: 4,
                    addr_name: "ZPY",
                    operation: Cpu::STX,
                    address_mode: Cpu::ZPY,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "TYA",
                    cycles: 2,
                    addr_name: "IMP",
                    operation: Cpu::TYA,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "STA",
                    cycles: 5,
                    addr_name: "ABSY",
                    operation: Cpu::STA,
                    address_mode: Cpu::ABSY,
                },
                Instruction {
                    name: "TXS",
                    cycles: 2,
                    addr_name: "IMP",
                    operation: Cpu::TXS,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "STA",
                    cycles: 5,
                    addr_name: "ABSX",
                    operation: Cpu::STA,
                    address_mode: Cpu::ABSX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                // ROW A
                Instruction {
                    name: "LDY",
                    cycles: 2,
                    addr_name: "IMM",
                    operation: Cpu::LDY,
                    address_mode: Cpu::IMM,
                },
                Instruction {
                    name: "LDA",
                    cycles: 6,
                    addr_name: "INDX",
                    operation: Cpu::LDA,
                    address_mode: Cpu::INDX,
                },
                Instruction {
                    name: "LDX",
                    cycles: 2,
                    addr_name: "IMM",
                    operation: Cpu::LDX,
                    address_mode: Cpu::IMM,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "LDY",
                    cycles: 3,
                    addr_name: "ZP",
                    operation: Cpu::LDY,
                    address_mode: Cpu::ZP,
                },
                Instruction {
                    name: "LDA",
                    cycles: 3,
                    addr_name: "ZP",
                    operation: Cpu::LDA,
                    address_mode: Cpu::ZP,
                },
                Instruction {
                    name: "LDX",
                    cycles: 3,
                    addr_name: "ZP",
                    operation: Cpu::LDX,
                    address_mode: Cpu::ZP,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "TAY",
                    cycles: 2,
                    addr_name: "IMP",
                    operation: Cpu::TAY,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "LDA",
                    cycles: 2,
                    addr_name: "IMM",
                    operation: Cpu::LDA,
                    address_mode: Cpu::IMM,
                },
                Instruction {
                    name: "TAX",
                    cycles: 2,
                    addr_name: "IMP",
                    operation: Cpu::TAX,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "LDY",
                    cycles: 4,
                    addr_name: "ABS",
                    operation: Cpu::LDY,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "LDA",
                    cycles: 4,
                    addr_name: "ABS",
                    operation: Cpu::LDA,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "LDX",
                    cycles: 4,
                    addr_name: "ABS",
                    operation: Cpu::LDX,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                // ROW B
                Instruction {
                    name: "BCS",
                    cycles: 2,
                    addr_name: "REL",
                    operation: Cpu::BCS,
                    address_mode: Cpu::REL,
                },
                Instruction {
                    name: "LDA",
                    cycles: 5,
                    addr_name: "INDY",
                    operation: Cpu::LDA,
                    address_mode: Cpu::INDY,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "LDY",
                    cycles: 4,
                    addr_name: "ZPX",
                    operation: Cpu::LDY,
                    address_mode: Cpu::ZPX,
                },
                Instruction {
                    name: "LDA",
                    cycles: 4,
                    addr_name: "ZPX",
                    operation: Cpu::LDA,
                    address_mode: Cpu::ZPX,
                },
                Instruction {
                    name: "LDX",
                    cycles: 4,
                    addr_name: "ZPY",
                    operation: Cpu::LDX,
                    address_mode: Cpu::ZPY,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "CLV",
                    cycles: 2,
                    addr_name: "IMP",
                    operation: Cpu::CLV,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "LDA",
                    cycles: 4,
                    addr_name: "ABSY",
                    operation: Cpu::LDA,
                    address_mode: Cpu::ABSY,
                },
                Instruction {
                    name: "TSX",
                    cycles: 2,
                    addr_name: "IMP",
                    operation: Cpu::TSX,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "LDY",
                    cycles: 4,
                    addr_name: "ABSX",
                    operation: Cpu::LDY,
                    address_mode: Cpu::ABSX,
                },
                Instruction {
                    name: "LDA",
                    cycles: 4,
                    addr_name: "ABSX",
                    operation: Cpu::LDA,
                    address_mode: Cpu::ABSX,
                },
                Instruction {
                    name: "LDX",
                    cycles: 4,
                    addr_name: "ABSY",
                    operation: Cpu::LDX,
                    address_mode: Cpu::ABSY,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                // ROW C
                Instruction {
                    name: "CPY",
                    cycles: 2,
                    addr_name: "IMM",
                    operation: Cpu::CPY,
                    address_mode: Cpu::IMM,
                },
                Instruction {
                    name: "CMP",
                    cycles: 6,
                    addr_name: "INDX",
                    operation: Cpu::CMP,
                    address_mode: Cpu::INDX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "CPY",
                    cycles: 3,
                    addr_name: "ZP",
                    operation: Cpu::CPY,
                    address_mode: Cpu::ZP,
                },
                Instruction {
                    name: "CMP",
                    cycles: 3,
                    addr_name: "ZP",
                    operation: Cpu::CMP,
                    address_mode: Cpu::ZP,
                },
                Instruction {
                    name: "DEC",
                    cycles: 5,
                    addr_name: "ZP",
                    operation: Cpu::DEC,
                    address_mode: Cpu::ZP,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "INY",
                    cycles: 2,
                    addr_name: "IMP",
                    operation: Cpu::INY,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "CMP",
                    cycles: 2,
                    addr_name: "IMM",
                    operation: Cpu::CMP,
                    address_mode: Cpu::IMM,
                },
                Instruction {
                    name: "DEX",
                    cycles: 2,
                    addr_name: "IMP",
                    operation: Cpu::DEX,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "CPY",
                    cycles: 4,
                    addr_name: "ABS",
                    operation: Cpu::CPY,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "CMP",
                    cycles: 4,
                    addr_name: "ABS",
                    operation: Cpu::CMP,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "DEC",
                    cycles: 6,
                    addr_name: "ABS",
                    operation: Cpu::DEC,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                //ROW D
                Instruction {
                    name: "BNE",
                    cycles: 2,
                    addr_name: "REL",
                    operation: Cpu::BNE,
                    address_mode: Cpu::REL,
                },
                Instruction {
                    name: "CMP",
                    cycles: 5,
                    addr_name: "INDY",
                    operation: Cpu::CMP,
                    address_mode: Cpu::INDY,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "CMP",
                    cycles: 4,
                    addr_name: "ZPX",
                    operation: Cpu::CMP,
                    address_mode: Cpu::ZPX,
                },
                Instruction {
                    name: "DEC",
                    cycles: 6,
                    addr_name: "ZPX",
                    operation: Cpu::DEC,
                    address_mode: Cpu::ZPX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "CLD",
                    cycles: 2,
                    addr_name: "IMP",
                    operation: Cpu::CLD,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "CMP",
                    cycles: 4,
                    addr_name: "ABSY",
                    operation: Cpu::CMP,
                    address_mode: Cpu::ABSY,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "CMP",
                    cycles: 4,
                    addr_name: "ABSX",
                    operation: Cpu::CMP,
                    address_mode: Cpu::ABSX,
                },
                Instruction {
                    name: "DEC",
                    cycles: 7,
                    addr_name: "ABSX",
                    operation: Cpu::DEC,
                    address_mode: Cpu::ABSX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                //ROW E
                Instruction {
                    name: "CPX",
                    cycles: 2,
                    addr_name: "IMM",
                    operation: Cpu::CPX,
                    address_mode: Cpu::IMM,
                },
                Instruction {
                    name: "SBC",
                    cycles: 6,
                    addr_name: "INDX",
                    operation: Cpu::SBC,
                    address_mode: Cpu::INDX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "CPX",
                    cycles: 3,
                    addr_name: "ZP",
                    operation: Cpu::CPX,
                    address_mode: Cpu::ZP,
                },
                Instruction {
                    name: "SBC",
                    cycles: 3,
                    addr_name: "ZP",
                    operation: Cpu::SBC,
                    address_mode: Cpu::ZP,
                },
                Instruction {
                    name: "INC",
                    cycles: 5,
                    addr_name: "ZP",
                    operation: Cpu::INC,
                    address_mode: Cpu::ZP,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "INX",
                    cycles: 2,
                    addr_name: "IMP",
                    operation: Cpu::INX,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "SBC",
                    cycles: 2,
                    addr_name: "IMM",
                    operation: Cpu::SBC,
                    address_mode: Cpu::IMM,
                },
                Instruction {
                    name: "NOP",
                    cycles: 2,
                    addr_name: "IMP",
                    operation: Cpu::NOP,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "CPX",
                    cycles: 4,
                    addr_name: "ABS",
                    operation: Cpu::CPX,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "SBC",
                    cycles: 4,
                    addr_name: "ABS",
                    operation: Cpu::SBC,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "INC",
                    cycles: 6,
                    addr_name: "ABS",
                    operation: Cpu::INC,
                    address_mode: Cpu::ABS,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                //ROW F
                Instruction {
                    name: "BEQ",
                    cycles: 2,
                    addr_name: "REL",
                    operation: Cpu::BEQ,
                    address_mode: Cpu::REL,
                },
                Instruction {
                    name: "SBC",
                    cycles: 5,
                    addr_name: "INDY",
                    operation: Cpu::SBC,
                    address_mode: Cpu::INDY,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "SBC",
                    cycles: 4,
                    addr_name: "ZPX",
                    operation: Cpu::SBC,
                    address_mode: Cpu::ZPX,
                },
                Instruction {
                    name: "INC",
                    cycles: 6,
                    addr_name: "ZPX",
                    operation: Cpu::INC,
                    address_mode: Cpu::ZPX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "SED",
                    cycles: 2,
                    addr_name: "IMP",
                    operation: Cpu::SED,
                    address_mode: Cpu::IMP,
                },
                Instruction {
                    name: "SBC",
                    cycles: 4,
                    addr_name: "ABSY",
                    operation: Cpu::SBC,
                    address_mode: Cpu::ABSY,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
                Instruction {
                    name: "SBC",
                    cycles: 4,
                    addr_name: "ABSX",
                    operation: Cpu::SBC,
                    address_mode: Cpu::ABSX,
                },
                Instruction {
                    name: "INC",
                    cycles: 7,
                    addr_name: "ABSX",
                    operation: Cpu::INC,
                    address_mode: Cpu::ABSX,
                },
                Instruction {
                    name: "???",
                    cycles: 0,
                    addr_name: "XXX",
                    operation: Cpu::XXX,
                    address_mode: Cpu::XXX,
                },
            ],
        }
    }
}
